Trivy-code update

diff --git a/.github/workflows/Build_Deploy.yaml b/.github/workflows/Build_Deploy.yaml
--- a/.github/workflows/Build_Deploy.yaml
+++ b/.github/workflows/Build_Deploy.yaml
@@ -56,8 +56,11 @@ jobs:
     steps:
       - name: Define Image Tags
         run: |
-          echo "IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/yelp-app:latest" >> $GITHUB_ENV
-          echo "IMAGE_TAG_SHA=${{ secrets.DOCKERHUB_USERNAME }}/yelp-app:${{ github.sha }}" >> $GITHUB_ENV
+          IMAGE_TAG="${{ secrets.DOCKERHUB_USERNAME }}/yelp-app:latest"
+          IMAGE_TAG_SHA="${{ secrets.DOCKERHUB_USERNAME }}/yelp-app:${{ github.sha }}"
+          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
+          echo "IMAGE_TAG_SHA=$IMAGE_TAG_SHA" >> $GITHUB_ENV
+          echo "✅ Image Tags Defined: $IMAGE_TAG and $IMAGE_TAG_SHA"
 
       - name: Verify Image Tags
         run: |
@@ -79,7 +82,8 @@ jobs:
     needs: docker_build
     steps:
       - name: Verify Image Exists Before Scanning
-        run: docker images | grep $IMAGE_TAG_SHA || (echo "❌ Image Not Found!" && exit 1)
+        run: |
+          docker images | grep $(echo $IMAGE_TAG_SHA | cut -d':' -f1) || (echo "❌ Image Not Found!" && exit 1)
 
       - name: Run Trivy Image Scan
         uses: aquasecurity/trivy-action@master
